### ISSUE TITLE
Error in Google Sheets

### ISSUE THREAD

**Issue by jfb2333** [SenorFernando/Scriptable#1]
Hi there!
First of all, the whole process looks pretty neat, respect for that!
Unfortunately, I encountered a problem and cannot find out the issue. Both the shortcut and widget work fine, but there seems to be a parsing error in Google Sheets with the formula in column D 

=IFERROR(QUERY(A$7:B, "select A where B = '"&C2&"' order by A desc limit 1"),"Never")

[https://ibb.co/Fmdq9rq](url)

Could you help me with that?

Thanks in advance!
Best,
Julius

**Comment by SenorFernando** [comment]
Hi @jfb2333 !
Glad you liked the project, it was a really good learning experience for me.

I tried to replicate your error and can't seem to do it, pasting the formula onto any Sheet gives me the expected value.

Perhaps a workaround would be replacing column D formulas with the following
=ArrayFormula(LOOKUP(2,1/($B$7:B=$C2),$A$7:$A))
=ArrayFormula(LOOKUP(2,1/($B$7:B=$C3),$A$7:$A))
=ArrayFormula(LOOKUP(2,1/($B$7:B=$C4),$A$7:$A))
=ArrayFormula(LOOKUP(2,1/($B$7:B=$C5),$A$7:$A))

Not sure if you tried with another sheet. If you decide on that route, you need to replace the Sheet ID on the logger.gs Script and on the first row of the "PlantGoogleData" file on the Scriptable folder in Files (the IOS app) 

Hope this helps

**Comment by jfb2333** [comment]
Hi Fernando,
thanks for the quick reply! Now it works perfectly fine!
Your idea got me experimenting a bit (am a total novice with Javascript), and I would like to transform this into a project dashboard. For that i´d like to have more than 4 items, is there any specific reason why you limited it to 4? Other than the Font in the Widget might have to be very small?

Thanks!

**Comment by SenorFernando** [comment]
@jfb2333 glad to hear it worked!

It's limited to 4 since I only have 4 plants IRL, also, the font would need to be smaller to fit more items (I'm using the small widget).

Let me know if you publish your project, I'd love to take a look.
